env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - GO111MODULE=on

jobs:
  include:
  - stage: test
    language: go
    go: 1.11.x
    before_install:
      - go get github.com/mattn/goveralls
    script:
      - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.15.0
      - golangci-lint run
      - go test -v -race ./... -coverprofile=qo100-dedrift.coverprofile
      - goveralls -coverprofile=qo100-dedrift.coverprofile -service travis-ci
  - stage: tagBuilds
    language: go
    go: 1.11.x
    script:
      - git describe --exact-match --tags HEAD 2>> /dev/null && export TRAVIS_TAG="`git describe --exact-match --tags HEAD`"; echo ""
      - "./travis-build.sh"

deploy:
  provider: releases
  file_glob: true
  file: bins/*
  skip_cleanup: true
  api_key:
    secure: lRobyMEPluNecwcLV88BkpnonGPsKF5QxLZVBwzz8qwifP4/RVGaxnP7MMVG8BZmQ38yeJ7SvDTUaiedinVV/S2i+K1VUICGWjxQYGZ8SBU+WIoykOhB86+MYFZQxwCW6X4Elk/RZAEYBNWXFrRfcqVzsu9ugm6AORYygCwXBa6rYiQnOJuOF+mQ7CKHrIGcWkcW7ZPSTO0GCk+N4aecIpzDFr4VTQPNyok55gdjj7Xxy2TsOL/vXTddAepdkU/ez79qIP0GqX9G1blSWNvXL82PtbbQZt+j1XofZLwN8rYsVwPcXBa4cqgWYMbCKwptmmqHncs997QBJBTJEUn2jqqfQPaaSO86Xp5HVH70IpyrkP969O5JqE+L+m64BQB//0BeozEiYFNSt50asLLzIufoOFW/kPZS9/aC71fo3gwWyrma2CAHmLassy4ImZ6dJ9lkd7L4XlE1iflrDPWTikfxorLl8O/XPZxhQmhKvKPGZ2ku9by0anE57akFv6MSyJLCKglXy8H+/XZCLIWe58BKyiGY86LiPywFJBdbfAOt7VvKz/g50re4aHim8ui9YftxHJNFr5XsCSlOp2eKb59mlct3QDB56y7WS3P6KYfJj4s0gs9FD88FANDwB0w5RfiMNaZBsneh4/rCesXDBn880bY+oEtZzTyTCpr79jU=
  on:
    tags: true
    repo: racerxdl/qo100-dedrift
